spring:
  application:
    name: breadkun-backend
  profiles:
    active: master

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics
      base-path: /management

server:
  port: 65477
  servlet:
    encoding:
      charset: UTF-8

springdoc:
  swagger-ui:
    path: /api-docs
  group-configs:
    - group: cafe-menu
      paths-to-match:
        - /api/cafe/menus/**
    - group: cafe-cart
      paths-to-match:
        - /api/cafe/carts/**