name: Build and Deploy

on:
  push:
    branches:
      - master

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    env:
      TARGET_BRANCH: ${{ github.ref_name }}

    steps:
      - name: Checkout the repository code
        uses: actions/checkout@v4

      - name: Set up Java 17 and Gradle cache
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Set environment variables based on branch
        run: |
          if [ "${{ env.TARGET_BRANCH }}" == "master" ]; then
            echo "SSH_PRIVATE_KEY=$(echo "${{ secrets.MASTER_SSH_PRIVATE_KEY }}" | tr -d '\n')" >> $GITHUB_ENV
            echo "REMOTE_HOST=${{ secrets.MASTER_SSH_HOST }}" >> $GITHUB_ENV
            echo "REMOTE_USER=${{ secrets.MASTER_SSH_USERNAME }}" >> $GITHUB_ENV
            echo "REMOTE_PORT=${{ secrets.MASTER_SSH_PORT }}" >> $GITHUB_ENV
            echo "DB_URL=${{ secrets.MASTER_DB_URL }}" >> $GITHUB_ENV
            echo "DB_USERNAME=${{ secrets.MASTER_DB_USERNAME }}" >> $GITHUB_ENV
            echo "DB_PASSWORD=${{ secrets.MASTER_DB_PASSWORD }}" >> $GITHUB_ENV
          fi

      - name: Dynamically set active profile from TARGET_BRANCH and build with Gradle
        run: ./gradlew build --no-daemon -P spring.profiles.active=${{ env.TARGET_BRANCH }}

      - name: Build Docker image and tag by branch
        run: docker build -t breadkun-backend:${{ env.TARGET_BRANCH }} .

      - name: Save Docker image
        run: docker save breadkun-backend:${{ env.TARGET_BRANCH }} -o breadkun-backend-${{ env.TARGET_BRANCH }}.tar

      - name: Clean up, Deploy, and Run Docker image
        uses: easingthemes/ssh-deploy@v5.1.0
        with:
          SSH_PRIVATE_KEY: ${{ env.SSH_PRIVATE_KEY }}
          REMOTE_HOST: ${{ env.REMOTE_HOST }}
          REMOTE_USER: ${{ env.REMOTE_USER }}
          REMOTE_PORT: ${{ env.REMOTE_PORT }}
          SOURCE: breadkun-backend-${{ env.TARGET_BRANCH }}.tar
          TARGET: /home/${{ env.REMOTE_USER }}/breadkun-backend-${{ env.TARGET_BRANCH }}.tar
          SCRIPT_BEFORE: |
            docker stop breadkun-backend-${{ env.TARGET_BRANCH }}-container || true
            docker rm breadkun-backend-${{ env.TARGET_BRANCH }}-container || true
            docker rmi breadkun-backend:${{ env.TARGET_BRANCH }} || true
            rm -f /home/${{ env.REMOTE_USER }}/breadkun-backend-${{ env.TARGET_BRANCH }}.tar
          SCRIPT_AFTER: |
            docker load -i /home/${{ env.REMOTE_USER }}/breadkun-backend-${{ env.TARGET_BRANCH }}.tar
            docker run -d \
              --name breadkun-backend-${{ env.TARGET_BRANCH }}-container  \
              -p 8080:8080 \
              -e DB_URL=${{ env.DB_URL }} \
              -e DB_USERNAME=${{ env.DB_USERNAME }} \
              -e DB_PASSWORD=${{ env.DB_PASSWORD }} \
              breadkun-backend:${{ env.TARGET_BRANCH }}
            sudo docker update --restart always breadkun-backend-${{ env.TARGET_BRANCH }}-container