name: Build and Deploy using Docker Compose

on:
  push:
    branches:
      - master

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository code
        uses: actions/checkout@v4

      - name: Set up Java 17 and Gradle cache
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Build and Run tests with environment variables
        run: |
          export BREADKUN_DB_URL=${{ secrets.BREADKUN_DB_URL }}
          export BREADKUN_DB_USERNAME=${{ secrets.BREADKUN_DB_USERNAME }}
          export BREADKUN_DB_PASSWORD=${{ secrets.BREADKUN_DB_PASSWORD }}
          ./gradlew build test --no-daemon -Dspring.profiles.active=master

      # 루트 경로의 Dockerfile로 이미지 굽기
      - name: Build Docker image and tag by branch
        run: docker build -t ciabatta-core:master .

      - name: Save Docker image
        run: docker save ciabatta-core:master -o ciabatta-core-master.tar

      - name: Clean up, Deploy, and Run Docker image
        uses: easingthemes/ssh-deploy@v5.1.0
        with:
          SSH_PRIVATE_KEY: ${{ secrets.MASTER_SSH_PRIVATE_KEY }}
          REMOTE_HOST: ${{ secrets.MASTER_SSH_HOST }}
          REMOTE_USER: ${{ secrets.MASTER_SSH_USERNAME }}
          REMOTE_PORT: ${{ secrets.MASTER_SSH_PORT }}
          SOURCE: ciabatta-core-master.tar
          TARGET: /home/${{ secrets.MASTER_SSH_USERNAME }}/ciabatta-core-master.tar
          SCRIPT_BEFORE: |
            docker stop ciabatta-core-master-container || true
            docker rm ciabatta-core-master-container || true
            docker rmi ciabatta-core:master || true
            rm -f /home/${{ secrets.MASTER_SSH_USERNAME }}/ciabatta-core-master.tar
          SCRIPT_AFTER: |
            docker load -i /home/${{ secrets.MASTER_SSH_USERNAME }}/ciabatta-core-master.tar
            docker compose -f /home/${{ secrets.MASTER_SSH_USERNAME }}/docker-compose.yaml up -d ciabatta-core